name: build-immortalwrt

on:
  # schedule: [ cron: 0 2 */7 * * ]
  # watch:
  #   types: started
  workflow_dispatch:
    inputs:
      branch:
        description: '选择源码仓库分支'
        required: true
        default: 'openwrt-23.05'
        type: choice
        options: [master, openwrt-23.05, openwrt-21.02, openwrt-18.06, openwrt-18.06-k5.4]

      target:
        description: '选择要编译的机型'
        required: true
        default: 'x86_64'
        type: choice
        options: [x86_64, r1-plus-lts, r2c, r2s, r4s, newifi-d2, asus_rt-n16, phicomm_k2p, armvirt-64-default]

      ip:
        description: '设置web登录IP'
        required: false
        default: '192.168.2.1'

      partsize:
        description: '设置rootfs大小'
        required: false
        default: '800'

      free_disk:
        description: '释放磁盘空间'
        required: false
        default: 'false'
        type: choice
        options: [no, losetup, plus]

env:
  UPLOAD_BIN_DIR: false
  UPLOAD_ARTIFACT: true
  UPLOAD_RELEASE: true
  PACKAGED_STATUS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    name: immortalwrt-${{ github.event.inputs.branch }}-${{ github.event.inputs.target }}

    permissions:
      contents: write

    env:
      REPO_BRANCH: ${{ github.event.inputs.branch }}
      TARGET_DEVICE: ${{ github.event.inputs.target }}
      DEFAULT_IP: ${{ github.event.inputs.ip }}
      PART_SIZE: ${{ github.event.inputs.partsize }}

    steps:
    - name: View System Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "==========================CPU信息=========================="
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU线程数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "==========================内存信息=========================="
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "==========================硬盘信息=========================="
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Free Disk Space
      if: github.event.inputs.free_disk == 'plus'
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Create Simulated Disk
      if: github.event.inputs.free_disk == 'losetup' || github.event.inputs.free_disk == 'plus'
      run: |
        MNT_SIZE=$((($(df --block-size=1024 --output=avail /mnt | tail -1) - 1024*1024*1) * 1024))
        sudo fallocate -l $MNT_SIZE /mnt/mnt.img
        MNT_NAME=$(sudo losetup -Pf --show /mnt/mnt.img)
        sudo pvcreate -f $MNT_NAME
        ROOT_SIZE=$((($(df --block-size=1024 --output=avail / | tail -1) - 1024*1024*4) * 1024))
        sudo fallocate -l $ROOT_SIZE /root.img
        ROOT_NAME=$(sudo losetup -Pf --show /root.img)
        sudo pvcreate -f $ROOT_NAME
        sudo vgcreate actions $MNT_NAME $ROOT_NAME
        sudo lvcreate -n disk -l 100%FREE actions
        LV_NAME=$(sudo lvscan | awk -F "'" '{print $2}')
        sudo mkfs.btrfs -L combinedisk $LV_NAME
        sudo mount -o compress=zstd $LV_NAME $GITHUB_WORKSPACE
        sudo chown -R runner:runner $GITHUB_WORKSPACE && df -hT

    - name: Checkout Repo
      uses: actions/checkout@v4.2.0

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        (docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo swapoff -a && sudo rm -f /swapfile /mnt/swapfile
        sudo -E apt-get -y update
        sudo -E apt-get -y install clang rename $(curl -fsSL is.gd/depends_ubuntu_2204)
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean) &
        sudo -E timedatectl set-timezone "$TZ"

    - name: Load Compile Script
      run: chmod +x immortalwrt.sh && ./immortalwrt.sh

    - name: Delete Old Toolchain
      if: steps.toolchain.conclusion == 'success' && !cancelled()
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: toolchain
        assets: '${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}.*'
        fail-if-no-assets: false
        fail-if-no-release: false

    - name: Upload Toolchain To Release
      if: env.PACKAGED_STATUS != 'true'
      uses: softprops/action-gh-release@v2.0.8
      with:
        name: ${{ env.EMOJI }} toolchain-cache ${{ env.EMOJI }}
        tag_name: toolchain
        token: ${{ secrets.GITHUB_TOKEN }}
        files: output/${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}.*
        body: OpenWrt 工具链缓存
#        with:
#          files: Release.txt

    - name: Upload OpenWrt To Release
      if: env.PACKAGED_STATUS == 'true'
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.EMOJI }} toolchain-cache ${{ env.EMOJI }}
        allowUpdates: true
        replacesArtifacts: true
        tag: toolchain
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: output/${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}.*
        body: OpenWrt 工具链缓存
